# Generated by Django 5.2.7 on 2026-05-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_investment_approved_alter_investment_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='category',
            field=models.CharField(default='Tesla (TSLA)', max_length=100),
        ),
        migrations.AlterField(
            model_name='investment',
            name='daily_roi',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
