# Generated by Django 5.2.7 on 2026-06-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_investment_category_alter_investment_daily_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
