# Generated by Django 5.2.7 on 2026-06-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='type',
            field=models.CharField(choices=[('stock', 'Stock'), ('plan', 'Plan')], default='stock', max_length=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
