# Generated by Django 5.2.7 on 2026-06-15 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_copytradingsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytradingsubscription',
            name='copy_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copytradingsubscription',
            name='copy_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copytradingsubscription',
            name='duration_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='copytradingsubscription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BotSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Starter', 'Starter'), ('Pro', 'Pro'), ('Institutional', 'Institutional')], default='Starter', max_length=20)),
                ('billing_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('plan_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_subscriptions', to='api.investor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
