# Generated by Django 5.2.7 on 2026-06-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_copytradingsubscription_copy_ends_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License")], default='national_id', max_length=20)),
                ('id_front', models.ImageField(upload_to='kyc/id_front/')),
                ('id_back', models.ImageField(upload_to='kyc/id_back/')),
                ('selfie', models.ImageField(upload_to='kyc/selfies/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to='api.investor')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
