# Generated by Django 5.2.7 on 2026-06-16 18:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_kycsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='deposit_proof'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='investment_proof'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='id_back',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='kyc_id_back'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='id_front',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='kyc_id_front'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='selfie',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='kyc_selfie'),
        ),
    ]
